[build]
target="thumbv6m-none-eabi"
linker = "flip-link"
rustflags = [
  "-C", "link-arg=--nmagic",
  "-C", "link-arg=-Tlink.x",
  # not using defmt
  #"-C", "link-arg=-Tdefmt.x",
  # Code-size optimizations.
  #   trap unreachable can save a lot of space, but requires nightly compiler.
  #   uncomment the next line if you wish to enable it
  # "-Z", "trap-unreachable=no",
  "-C", "no-vectorize-loops",
]

[target.thumbv6m-none-eabi]
runner = "elf2uf2-rs -d"
